version: '3'
services:
  backend:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: nodemon dist/app.js
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - nestjs-network
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  postgres-data: